services:
  local:
    pull_policy: build
    ports:
      - 3000:3000
      - 5173:5173
    build:
      context: .
      dockerfile: ./docker/dev.dockerfile
    image: nexus:local
    env_file:
      - .env
    #environment:
    #- DATABASE_URL=${POSTGRES_LOCAL_URL}
    volumes:
      - ./apps:/app/apps
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/server/node_modules
      - /app/apps/client/node_modules
    depends_on:
      #- postgres-local
      - redis-local
    restart: unless-stopped

  #postgres-local:
  #  image: postgres:14.17
  #  ports:
  #    - 5432:5432
  #  environment:
  #    - POSTGRES_DB=${POSTGRES_DB}
  #    - POSTGRES_USER=${POSTGRES_USER}
  #    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #  restart: unless-stopped
  #  volumes:
  #    - pg_nexus_dev:/var/lib/postgresql/data

  redis-local:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_nexus_dev:/data
    command: >
      --requirepass ${REDIS_PASSWORD}

volumes:
  #pg_nexus_dev:
  #  external: true
  redis_nexus_dev:
    external: true
